# -*- coding: utf-8 -*-
"""Serve a set of clips to a real device, one card each, labelled from ffprobe.

Why this is a committed script rather than a throwaway in /tmp: the 2026-08-25
investigation into why 103 of 109 library files would not play on an iPad needed
exactly this, got it wrong twice, and then threw it away.

Two of those mistakes are designed out here rather than written down:

1. **`python3 -m http.server` cannot be used for this.** It answers no byte-range
   requests, and iOS Safari refuses to play video from a server that does not.
   Every clip comes back "broken" -- a false negative for the entire run. The 206
   handling below is the load-bearing part of this file.

2. **A single-variable test has to be *readable* as single-variable.** The first
   run put the control and the first variant next to each other; they were the
   same video, so the two cards looked identical, and the first answer that came
   back ("(1) plays") turned out to be the control being tapped twice. Nothing
   was wrong with the design -- only with what a person could see. So every label
   here is generated by running `ffprobe` on the file being served, never typed
   in: a label cannot drift from the artifact it names if it is derived from it.

Usage::

    python3 scripts/codec-probe-server.py data/videos/a.mp4 data/videos/b.mp4
    python3 scripts/codec-probe-server.py --port 8503 --bind 0.0.0.0 clips/*.mp4

Then open ``http://<this-host>:<port>/`` on the device under test and tap each
card. The page reports what the browser itself said (`MediaError` code, decoded
resolution, duration), so the result does not depend on someone describing what
they saw.

This is a manual rig: it serves local files to a device on your own network, it
does not authenticate, and it is meant to be run for a few minutes and stopped.
"""
from __future__ import annotations

import argparse
import http.server
import json
import os
import re
import socket
import socketserver
import subprocess
import sys
from typing import Dict, List, Optional, Tuple

_RANGE_RE = re.compile(r"bytes=(\d*)-(\d*)")
_CHUNK = 262144


def parse_range(header: Optional[str], size: int) -> Tuple[int, int, bool]:
    """Resolve a Range header against a file size.

    Returns ``(start, end_inclusive, is_partial)``. A missing or unparseable
    header yields the whole file with ``is_partial=False``, and the caller sends
    200 rather than 206. ``start >= size`` is the caller's cue to send 416.

    Split out as a pure function on purpose: this is the one piece here whose
    silent failure looks exactly like "the device cannot decode this codec".
    """
    if not header:
        return 0, size - 1, False
    m = _RANGE_RE.match(header.strip())
    if not m:
        return 0, size - 1, False
    g1, g2 = m.group(1), m.group(2)
    if g1:
        start = int(g1)
        end = min(int(g2), size - 1) if g2 else size - 1
    elif g2:
        # Suffix form: "bytes=-500" asks for the last 500 bytes.
        start = max(0, size - int(g2))
        end = size - 1
    else:
        # "bytes=-" is neither; treat it as no range rather than as byte 0.
        return 0, size - 1, False
    return start, end, True


def probe(path: str) -> Dict[str, str]:
    """Ask ffprobe what actually landed.

    Never raises. An unprobeable clip is still worth serving; it just gets a
    label that says so, which is itself the useful information on the page.
    """
    out = {"video": "?", "audio": "?", "duration": "?", "size": ""}
    try:
        out["size"] = "%.1f MB" % (os.path.getsize(path) / 1048576.0)
    except OSError:
        pass
    try:
        raw = subprocess.check_output(
            ["ffprobe", "-v", "error", "-print_format", "json",
             "-show_streams", "-show_format", path],
            stderr=subprocess.STDOUT,
        )
        data = json.loads(raw.decode("utf-8", "replace"))
    except Exception as exc:  # ffprobe absent, not on PATH, unreadable file...
        out["video"] = "ffprobe failed (%s)" % type(exc).__name__
        return out
    for s in data.get("streams", []):
        kind = s.get("codec_type")
        if kind == "video" and out["video"] == "?":
            out["video"] = s.get("codec_name", "?")
        elif kind == "audio" and out["audio"] == "?":
            out["audio"] = s.get("codec_name", "?")
    try:
        out["duration"] = "%.1fs" % float(data.get("format", {}).get("duration", 0))
    except (TypeError, ValueError):
        pass
    return out


def card_label(path: str, info: Dict[str, str]) -> str:
    """The one line a person reads to tell two cards apart.

    Filename first, because two clips with identical codecs are told apart only
    by which file they are -- that was the failure mode. Codecs second, because
    that is usually the variable under test.
    """
    bits = [os.path.basename(path), "%s + %s" % (info["video"], info["audio"])]
    if info["duration"] != "?":
        bits.append(info["duration"])
    if info["size"]:
        bits.append(info["size"])
    return " · ".join(bits)


PAGE_HEAD = """<!doctype html>
<html lang="zh-Hant"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>codec probe</title>
<style>
 body{font:16px/1.6 -apple-system,system-ui,sans-serif;margin:0 auto;padding:20px;
      background:#111;color:#eee;max-width:760px}
 h1{font-size:19px;margin:0 0 4px}
 .sub{color:#999;font-size:14px;margin:0 0 24px}
 .card{border:1px solid #333;border-radius:10px;padding:14px;margin:0 0 20px;background:#181818}
 h2{font-size:15px;margin:0 0 6px;font-family:ui-monospace,Menlo,monospace;color:#6cf;
    word-break:break-all}
 video{width:100%;background:#000;border-radius:6px;display:block}
 .err{color:#f77;font-size:13px;margin-top:8px;min-height:18px}
 .ok{color:#7d7}
</style></head><body>
<h1>codec probe</h1>
<p class="sub">Tap each card. Every title is read off that file by ffprobe, not
typed in. The line under each player is what the browser itself reported.</p>
"""

PAGE_TAIL = """<script>
document.querySelectorAll('video').forEach(function(v){
  var out = document.getElementById('e_' + v.dataset.k);
  v.addEventListener('error', function(){
    var e = v.error, m = {1:'ABORTED',2:'NETWORK',3:'DECODE',4:'SRC_NOT_SUPPORTED'};
    out.textContent = 'FAIL error: ' + (e ? (m[e.code] || e.code) : '?')
      + (e && e.message ? ' - ' + e.message : '');
  });
  v.addEventListener('loadedmetadata', function(){
    out.className = 'err ok';
    out.textContent = 'OK metadata: ' + Math.round(v.duration) + 's, '
      + v.videoWidth + 'x' + v.videoHeight;
  });
  v.addEventListener('playing', function(){
    out.className = 'err ok';
    out.textContent = 'OK playing: ' + v.videoWidth + 'x' + v.videoHeight
      + ' (audio is not observable from here - listen)';
  });
});
</script>
</body></html>"""


def build_page(clips: List[Tuple[str, str]]) -> bytes:
    """clips: list of ``(key, absolute path)``.

    Labels are probed per request rather than at startup, so swapping a file on
    disk changes the page without a restart.
    """
    parts = [PAGE_HEAD]
    for key, path in clips:
        parts.append(
            '<div class="card"><h2>%s</h2>'
            '<video data-k="%s" controls playsinline preload="metadata" src="/v/%s"></video>'
            '<div class="err" id="e_%s"></div></div>'
            % (card_label(path, probe(path)), key, key, key)
        )
    parts.append(PAGE_TAIL)
    return "\n".join(parts).encode("utf-8")


def make_handler(clips: List[Tuple[str, str]]):
    by_key = dict(clips)

    class Handler(http.server.BaseHTTPRequestHandler):
        protocol_version = "HTTP/1.1"

        def log_message(self, fmt, *args):
            pass

        def do_GET(self):
            if self.path in ("/", "/index.html"):
                body = build_page(clips)
                self.send_response(200)
                self.send_header("Content-Type", "text/html; charset=utf-8")
                self.send_header("Content-Length", str(len(body)))
                self.send_header("Cache-Control", "no-store")
                self.end_headers()
                self.wfile.write(body)
                return
            if self.path.startswith("/v/"):
                path = by_key.get(self.path[3:])
                if path is None:
                    self.send_error(404)
                    return
                self._serve(path)
                return
            self.send_error(404)

        def _serve(self, path):
            try:
                size = os.path.getsize(path)
            except OSError:
                self.send_error(404)
                return
            start, end, partial = parse_range(self.headers.get("Range"), size)
            if start >= size:
                self.send_response(416)
                self.send_header("Content-Range", "bytes */%d" % size)
                self.send_header("Content-Length", "0")
                self.end_headers()
                return
            length = end - start + 1
            self.send_response(206 if partial else 200)
            self.send_header("Content-Type", "video/mp4")
            self.send_header("Accept-Ranges", "bytes")
            self.send_header("Content-Length", str(length))
            if partial:
                self.send_header("Content-Range", "bytes %d-%d/%d" % (start, end, size))
            self.end_headers()
            with open(path, "rb") as f:
                f.seek(start)
                left = length
                while left > 0:
                    chunk = f.read(min(_CHUNK, left))
                    if not chunk:
                        break
                    try:
                        self.wfile.write(chunk)
                    except (BrokenPipeError, ConnectionResetError):
                        return
                    left -= len(chunk)

    return Handler


class Server(socketserver.ThreadingTCPServer):
    allow_reuse_address = True
    daemon_threads = True


def _lan_ip() -> str:
    """Best-effort address to print. Nothing depends on it being right."""
    s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    try:
        s.connect(("8.8.8.8", 80))
        return s.getsockname()[0]
    except OSError:
        return "127.0.0.1"
    finally:
        s.close()


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description="Serve clips to a device, one card each.")
    ap.add_argument("clips", nargs="+", help="video files to serve, one card each")
    ap.add_argument("--port", type=int, default=8503)
    ap.add_argument("--bind", default="0.0.0.0")
    args = ap.parse_args(argv)

    missing = [c for c in args.clips if not os.path.isfile(c)]
    if missing:
        # Loudly, before binding. A missing clip would otherwise become a 404
        # card that reads exactly like "this device cannot play it".
        sys.stderr.write("not found:\n  %s\n" % "\n  ".join(missing))
        return 2

    clips = [("c%d" % i, os.path.abspath(p)) for i, p in enumerate(args.clips)]
    print("codec probe:", flush=True)
    for key, path in clips:
        print("  %s" % card_label(path, probe(path)), flush=True)
    print("\n  http://%s:%d/   (Ctrl-C to stop)" % (_lan_ip(), args.port), flush=True)
    Server((args.bind, args.port), make_handler(clips)).serve_forever()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
